<?php

namespace Turnos\Core\Proxies\__CG__\Turnos\Core\model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Profesional extends \Turnos\Core\model\Profesional implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'nombre', 'matricula', 'domicilio', 'nroDocumento', 'tipoDocumento', 'telefonoFijo', 'telefonoMovil', 'email', 'cuit', 'condicionIVA', 'categoria', 'user', 'especialidades');
        }

        return array('__isInitialized__', 'nombre', 'matricula', 'domicilio', 'nroDocumento', 'tipoDocumento', 'telefonoFijo', 'telefonoMovil', 'email', 'cuit', 'condicionIVA', 'categoria', 'user', 'especialidades');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Profesional $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatricula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatricula', array());

        return parent::getMatricula();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatricula($matricula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatricula', array($matricula));

        return parent::setMatricula($matricula);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomicilio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomicilio', array());

        return parent::getDomicilio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomicilio($domicilio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomicilio', array($domicilio));

        return parent::setDomicilio($domicilio);
    }

    /**
     * {@inheritDoc}
     */
    public function getNroDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNroDocumento', array());

        return parent::getNroDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setNroDocumento($nroDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNroDocumento', array($nroDocumento));

        return parent::setNroDocumento($nroDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoDocumento', array());

        return parent::getTipoDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoDocumento($tipoDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoDocumento', array($tipoDocumento));

        return parent::setTipoDocumento($tipoDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoDocumentoOid($oid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoDocumentoOid', array($oid));

        return parent::setTipoDocumentoOid($oid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoFijo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoFijo', array());

        return parent::getTelefonoFijo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoFijo($telefonoFijo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoFijo', array($telefonoFijo));

        return parent::setTelefonoFijo($telefonoFijo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoMovil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoMovil', array());

        return parent::getTelefonoMovil();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoMovil($telefonoMovil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoMovil', array($telefonoMovil));

        return parent::setTelefonoMovil($telefonoMovil);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCuit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCuit', array());

        return parent::getCuit();
    }

    /**
     * {@inheritDoc}
     */
    public function setCuit($cuit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCuit', array($cuit));

        return parent::setCuit($cuit);
    }

    /**
     * {@inheritDoc}
     */
    public function getCondicionIVA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCondicionIVA', array());

        return parent::getCondicionIVA();
    }

    /**
     * {@inheritDoc}
     */
    public function getCondicionIVAOid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCondicionIVAOid', array());

        return parent::getCondicionIVAOid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCondicionIVA($condicionIVA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCondicionIVA', array($condicionIVA));

        return parent::setCondicionIVA($condicionIVA);
    }

    /**
     * {@inheritDoc}
     */
    public function setCondicionIVAOid($oid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCondicionIVAOid', array($oid));

        return parent::setCondicionIVAOid($oid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoria', array());

        return parent::getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoria($categoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', array($categoria));

        return parent::setCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function addEspecialidad(\Turnos\Core\model\Especialidad $especialidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEspecialidad', array($especialidad));

        return parent::addEspecialidad($especialidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getEspecialidades()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEspecialidades', array());

        return parent::getEspecialidades();
    }

    /**
     * {@inheritDoc}
     */
    public function setEspecialidades($especialidades)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEspecialidades', array($especialidades));

        return parent::setEspecialidades($especialidades);
    }

    /**
     * {@inheritDoc}
     */
    public function hasEspecialidadByOid($oid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasEspecialidadByOid', array($oid));

        return parent::hasEspecialidadByOid($oid);
    }

    /**
     * {@inheritDoc}
     */
    public function getOid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getOid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOid', array());

        return parent::getOid();
    }

    /**
     * {@inheritDoc}
     */
    public function setOid($oid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOid', array($oid));

        return parent::setOid($oid);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', array());

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', array($version));

        return parent::setVersion($version);
    }

}
